name: Build OpenWrt for Phicomm K2P

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget

    - name: Clone OpenWrt
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure Phicomm K2P without IPv6
      run: |
        cd openwrt
        make menuconfig <<EOF
        Target System  ---> MediaTek Ralink MIPS
        Subtarget     ---> MT7621 based boards
        Target Profile ---> Phicomm K2P
        EOF
        # Non-interaktif: Hapus IPv6 dari .config
        sed -i '/CONFIG_IPV6/d' .config
        echo "# Disable IPv6" >> .config
        echo "CONFIG_IPV6=n" >> .config
        make defconfig

    - name: Build
      run: |
        cd openwrt
        make -j$(nproc)

    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: OpenWrt-Phicomm-K2P
        path: openwrt/bin/targets/
